### ISSUE TITLE
Follow python naming convension

### ISSUE THREAD

**Issue by zeezoich** [0kba/python#1]
https://github.com/0kba/python/blob/9c70a0b9cd0ca2559c99faa6e8c65995cf68e4b3/homework_10-14-2018/combine_infinite_lists.py#L5

Python has helpful style guid here 
https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

> Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.

When you name a variable, make the name easy to read, for example combined_result_list instead of combinedresultlist.

**Comment by 0kba** [comment]
done

**Comment by AbdelOuaffar** [comment]
Got it.😴
