### ISSUE TITLE
A function should do one thing and one thing only

### ISSUE THREAD

**Issue by zeezoich** [0kba/python#2]
https://github.com/0kba/python/blob/9c70a0b9cd0ca2559c99faa6e8c65995cf68e4b3/homework_10-14-2018/combine_infinite_lists.py#L10

Break your function into multiple functions, each of which does one thing and one thing only.
Create a function that knows how to flatten a list for n-dimensions to (n-1)-dimensions. Call that function repeatedly until you have a 1-dimension list.

**Comment by 0kba** [comment]
I couldn't break this code i think i might need your help on that ... i will keep trying until next class anyways.

**Comment by zeezoich** [comment]
Try for example to make your inner for loop a function and call it from your outer loop.
