### ISSUE TITLE
Follow style and naming conventions and create helper functions

### ISSUE THREAD

**Issue by zeezoich** [0kba/python#3]
https://github.com/0kba/python/blob/9c70a0b9cd0ca2559c99faa6e8c65995cf68e4b3/homework_10-14-2018/employee_info.py#L2

Don't do all the work in one function. Break it into smaller pieces, easier to read, debug and maintain. Very important.

**Comment by 0kba** [comment]
done

**Comment by zeezoich** [comment]
I don’t see changes. Think of all the pieces your program is doing. Can some of them be in their own functions?

Also use the string split function.
