### ISSUE TITLE
Range and Tests

### ISSUE THREAD

**Issue by zeezoich** [0kba/python#4]
https://github.com/0kba/python/blob/cf170e2c12f1f9603f1a52105ec54f71d056f93f/homework_10-28-18/fib2.py#L7

Why range here? Why not a while loop?

Test cases missing!

**Comment by 0kba** [comment]
1- test cases it was there but it didn't appear because it was after the line code   __main__() when i put it before it now it does appear ... why is that ?
2- i will try to use while instead of for and range.

**Comment by 0kba** [comment]
i used while instead of for and range .
